name: prolinked

services:
  redis:
    image: redis:7.4-rc-alpine
    networks:
      - prolinked-network  
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: localhost
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd!
      - MSSQL_LCID=1033
      - TZ=Europe/Athens
    ports:
      - 1433:1433
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P P@ssw0rd! -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
    networks: 
      - prolinked-network
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: localhost
    ports:
      - 10001:10001
    networks: 
      - prolinked-network

networks:
  prolinked-network:
    external: true