/**
 * ProLinked Web Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AdvertisementStatus } from './advertisementStatus';
import { EmploymentTypeEnum } from './employmentTypeEnum';
import { WorkArrangementEnum } from './workArrangementEnum';

export interface AdvertisementCUDto { 
    title?: string;
    description?: string;
    company?: string;
    location?: string;
    employmentType?: EmploymentTypeEnum;
    workArrangement?: WorkArrangementEnum;
    status?: AdvertisementStatus;
}