/**
 * ProLinked Web Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type EmploymentTypeEnum = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;

export const EmploymentTypeEnum = {
    NUMBER_0: 0 as EmploymentTypeEnum,
    NUMBER_1: 1 as EmploymentTypeEnum,
    NUMBER_2: 2 as EmploymentTypeEnum,
    NUMBER_3: 3 as EmploymentTypeEnum,
    NUMBER_4: 4 as EmploymentTypeEnum,
    NUMBER_5: 5 as EmploymentTypeEnum,
    NUMBER_6: 6 as EmploymentTypeEnum,
    NUMBER_7: 7 as EmploymentTypeEnum,
    NUMBER_8: 8 as EmploymentTypeEnum
};