/**
 * ProLinked Web Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UpdateIdentityDto { 
    newName?: string;
    newSurname?: string;
    newDateOfBirth?: Date;
    newPhoneNumber?: string;
    newSummary?: string;
    newJobTitle?: string;
    newCompany?: string;
    newCity?: string;
    newEmail?: string;
    newPassword?: string;
    oldPassword?: string;
}